apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: servicemonitor-template-assisted-installer-postgres
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      prometheus: app-sre
    name: servicemonitor-assisted-installer-postgres
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
      scheme: http
    namespaceSelector:
      matchNames:
      - ${NAMESPACE}
    selector:
      matchLabels:
        app: assisted-installer-prometheus-postgres-exporter
parameters:
- name: NAMESPACE
  value: ''
  required: true
